"""Pydantic models for request/response schemas."""
from datetime import datetime
from typing import Literal
from pydantic import BaseModel, Field


# ============================================================================
# Chat Models
# ============================================================================

class ChatAttachment(BaseModel):
    """Attachment for chat messages (e.g., images)."""
    id: str
    name: str
    mime_type: str
    size: int
    data: str  # base64 encoded data


class ChatMessage(BaseModel):
    """Single chat message."""
    role: Literal["user", "assistant"]
    content: str
    timestamp: datetime = Field(default_factory=datetime.now)
    tables: list["TableData"] | None = None  # Optional table data for assistant messages
    attachments: list[ChatAttachment] | None = None  # Optional attachments (e.g., images)


class ChatRequest(BaseModel):
    """Request body for chat endpoint."""
    message: str = Field(..., min_length=1, max_length=5000)
    session_id: str | None = None
    timezone: str | None = None  # IANA timezone from browser, e.g. "America/New_York"


class ChatHistoryItem(BaseModel):
    """Chat history item for listing sessions."""
    session_id: str
    title: str
    last_message: str
    timestamp: datetime
    message_count: int


class ChatSession(BaseModel):
    """Complete chat session with all messages."""
    session_id: str
    title: str
    messages: list[ChatMessage]
    created_at: datetime
    updated_at: datetime
    title_generated: bool = False  # True if title was generated by LLM
    user_id: str | None = None  # Owner of this session
    greeted: bool = False  # True if user has been greeted in this session


class CreateSessionRequest(BaseModel):
    """Request to create a new session."""
    title: str = Field(default="New Chat", max_length=200)


class CreateSessionResponse(BaseModel):
    """Response after creating a session."""
    session_id: str
    title: str
    created_at: datetime


class GenerateTitleRequest(BaseModel):
    """Request to generate a session title."""
    messages: list[ChatMessage]


class GenerateTitleResponse(BaseModel):
    """Response with generated title."""
    title: str


# ============================================================================
# Table Models
# ============================================================================

class TableColumn(BaseModel):
    """Table column definition."""
    header: str
    accessor: str


class TableData(BaseModel):
    """Table data structure for frontend."""
    columns: list[TableColumn]
    rows: list[dict]


# ============================================================================
# SSE Event Models
# ============================================================================

class SSETextEvent(BaseModel):
    """SSE event for text content."""
    type: Literal["text"] = "text"
    content: str


class SSETableEvent(BaseModel):
    """SSE event for table data."""
    type: Literal["table"] = "table"
    data: TableData


class SSEErrorEvent(BaseModel):
    """SSE event for errors."""
    type: Literal["error"] = "error"
    message: str


class SSEEndEvent(BaseModel):
    """SSE event to signal end of stream."""
    type: Literal["end"] = "end"


# ============================================================================
# Document Ingestion Models
# ============================================================================

class DocumentMetadata(BaseModel):
    """Metadata for an embedded document chunk."""
    document_id: str
    source_filename: str
    chunk_index: int
    total_chunks: int
    document_type: str | None = None
    summary: str | None = None
    keywords: list[str] | None = None
    created_at: datetime = Field(default_factory=datetime.now)


class DocumentUploadResponse(BaseModel):
    """Response after uploading and processing a document."""
    document_id: str
    filename: str
    chunks_created: int
    status: str
    message: str
